# Write your code here :-)
print("========================")
print("     Get Out of Here    ")
print("    By Darrick Russell  ")
print("========================")
print("")
print("Go away")
name = input("Who the hell are you??")
print(f"Screw you, {name}")